
import { GoogleGenAI, Modality } from "@google/genai";

const fileToBase64 = (file: File): Promise<string> => {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.readAsDataURL(file);
    reader.onload = () => {
      if (typeof reader.result !== 'string') {
        return reject(new Error('FileReader result is not a string'));
      }
      // result is "data:image/png;base64,..." - we need to strip the prefix
      resolve(reader.result.split(',')[1]);
    };
    reader.onerror = error => reject(error);
  });
};

export const generateHugImage = async (image1File: File, image2File: File): Promise<string> => {
    if (!process.env.API_KEY) {
        throw new Error("API_KEY environment variable is not set.");
    }
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

    const image1Base64 = await fileToBase64(image1File);
    const image2Base64 = await fileToBase64(image2File);

    const prompt = 'Create a single, new, very realistic photo where the person from the first image and the person from the second image are hugging each other affectionately. They should be placed in a beautiful, natural outdoor background like a serene park during a sunny day or a beach at sunset. The final image should look like a real photograph with natural lighting and shadows, blending the two people seamlessly.';

    const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash-image',
        contents: {
            parts: [
                {
                    inlineData: {
                        data: image1Base64,
                        mimeType: image1File.type,
                    },
                },
                {
                    inlineData: {
                        data: image2Base64,
                        mimeType: image2File.type,
                    },
                },
                {
                    text: prompt,
                },
            ],
        },
        config: {
            responseModalities: [Modality.IMAGE],
        },
    });

    if (response.candidates && response.candidates.length > 0) {
        for (const part of response.candidates[0].content.parts) {
            if (part.inlineData) {
                const base64ImageBytes: string = part.inlineData.data;
                return `data:image/png;base64,${base64ImageBytes}`;
            }
        }
    }
    
    throw new Error("No image was generated by the API. The response may have been blocked.");
};
